Adding additional links
Caitlin1306/nch-final-project pull request #36
Opened 2022-12-01 13:10 UTC by Caitlin1306

2022-12-02 12:30 UTC, missKatiaPunter requested changes

2022-12-02 12:30 UTC, missKatiaPunter commented on README.md
> +- [Team & Processes](#Team & Processes)
```suggestion
- [Team & Processes](#Team-&-Processes)
```

2022-12-02 12:34 UTC, T-J-Summer approved these changes

2022-12-03 16:11 UTC, missKatiaPunter approved these changes

2022-12-03 16:18 UTC, merged